before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews: 
- 
  name: harsh
  github:
    owner: wakatara
    name: homebrew-tap
  description: habit tracking for geeks. A minimalist CLI for examining your habits. 
  homepage: https://github.com/wakatara/harsh
  test: |
    system "#{bin}/harsh --version"
